version: '3'
services:
  camera-agent-1:
    container_name: camera-agent-1
    image: van15h/camera-agent:v1
    restart: always
    ports:
      - "35001:8080"
    networks:
      - airport_net

  camera-agent-2:
    container_name: camera-agent-2
    image: van15h/camera-agent:v1
    restart: always
    ports:
      - "35002:8080"
    networks:
      - airport_net

  collector:
    container_name: collector
    image: van15h/collector:v1
    restart: always
    volumes:
      - ./src/collector:/app
    ports:
      - "35010:8080"
    networks:
      - airport_net

  image-analysis:
    container_name: image-analysis
    image: van15h/image-analysis:v1
    restart: always
    ports:
      - "35020:8080"
    networks:
      - airport_net

  section-1:
    container_name: section-1
    image: van15h/section:v1
    environment:
      - SECTION=1
    restart: always
    volumes:
      - ./src/section:/app
    ports:
      - "35030:8080"
    networks:
      - airport_net

  face-recognition:
    container_name: face-recognition
    image: van15h/face-recognition:v1
    restart: always
    ports:
      - "35040:8080"
    networks:
      - airport_net

  alerts:
    container_name: alerts
    image: van15h/alerts:v1
    restart: always
    volumes:
      - ./src/alerts:/app
    ports:
      - "35050:8080"
    networks:
      - airport_net

  cpanel:
    container_name: cpanel
    image: van15h/cpanel:v1
    restart: always
    volumes:
      - ./src/cpanel:/app
    ports:
      - "35060:8080"
    networks:
      - airport_net

  frontend:
    container_name: frontend
    image: van15h/frontend:v1
    restart: always
    volumes:
      - ./src/frontend:/usr/share/nginx/html
    ports:
      - "35070:80"
    networks:
      - airport_net

networks:
  airport_net:
    driver: bridge
