apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-1-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-1
  template:
    metadata:
      labels:
        app: camera-agent-1
    spec:
      containers:
      - name: camera-agent-1
        image: ccuni/camera-agent:latest
        ports:
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-2-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-2
  template:
    metadata:
      labels:
        app: camera-agent-2
    spec:
      containers:
      - name: camera-agent-2
        image: ccuni/camera-agent:latest
        ports:
          - containerPort: 8080