apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: van15h/collector
        ports:
          - containerPort: 8080
        env:
        - name: URL_ALERTS
          value: "http://alerts:8080"
        - name: URL_IMAGE_ANALYZE
          value: "http://image-analysis:8080/frame"
        - name: URL_FACE_RECOGNITION
          value: "http://face-recognition:8080/frame"
