apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    app: alerts
    service: alerts
    project: airport
spec:
  selector:
    app: alerts
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-deploy
  labels:
    app: alerts
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts
      version: v1
  template:
    metadata:
      labels:
        app: alerts
        version: v1
    spec:
      containers:
      - name: alerts
        image: van15h/alerts:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: URL_CPANEL
          value: "http://cpanel.default.svc.cluster.local:8080/alert"
