apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    app: alerts
    service: alerts
    project: airport
spec:
  selector:
    app: alerts
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-deploy
  labels:
    app: alerts
    version: v1
    project: airport
  # annotations:
  #   sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts
      version: v1
  template:
    metadata:
      labels:
        app: alerts
        version: v1
    spec:
      containers:
      - name: alerts
        image: van15h/alerts:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: URL_MOMENTUM
          value: "http://momentum.default.svc.cluster.local:8080/alert"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3