apiVersion: v1
kind: Service
metadata:
  name: camera-agent-1
  labels:
    app: camera-agent-1
    service: camera-agent-1
    project: airport
spec:
  selector:
    app: camera-agent-1
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-1-deploy
  labels:
    app: camera-agent-1
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-1
      version: v1
  template:
    metadata:
      labels:
        app: camera-agent-1
        version: v1
    spec:
      containers:
      - name: camera-agent-1
        image: van15h/camera-agent:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: camera-agent-2
  labels:
    app: camera-agent-2
    service: camera-agent-2
    project: airport
spec:
  selector:
    app: camera-agent-2
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-2-deploy
  labels:
    app: camera-agent-2
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-2
      version: v1
  template:
    metadata:
      labels:
        app: camera-agent-2
        version: v1
    spec:
      containers:
      - name: camera-agent-2
        image: van15h/camera-agent:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "150m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3