apiVersion: v1
kind: Service
metadata:
  name: camera-agent-1
  labels:
    app: camera-agent-1
    service: camera-agent-1
spec:
  selector:
    app: camera-agent-1
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-1-deploy
  labels:
    app: camera-agent-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-1
      version: v1
  template:
    metadata:
      labels:
        app: camera-agent-1
        version: v1
    spec:
      containers:
      - name: camera-agent-1
        image: ccuni/camera-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: camera-agent-2
  labels:
    app: camera-agent-2
    service: camera-agent-2
spec:
  # type: NodePort
  selector:
    app: camera-agent-2
  ports:
  - name: http
    # protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-2-deploy
  labels:
    app: camera-agent-2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-2
      version: v1
  template:
    metadata:
      labels:
        app: camera-agent-2
        version: v1
    spec:
      containers:
      - name: camera-agent-2
        image: ccuni/camera-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080