apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app: collector
    service: collector
    project: airport
spec:
  selector:
    app: collector
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deploy
  labels:
    app: collector
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
      version: v1
  template:
    metadata:
      labels:
        app: collector
        version: v1
    spec:
      containers:
      - name: collector
        image: van15h/collector:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: URL_MOMENTUM
          value: "http://momentum.default.svc.cluster.local:8080/analysis"
        - name: URL_ALERTS
          value: "http://alerts.default.svc.cluster.local:8080"
        - name: URL_IMAGE_ANALYZE
          value: "http://image-analysis.default.svc.cluster.local:8080/frame"
        - name: URL_FACE_RECOGNITION
          value: "http://face-recognition.default.svc.cluster.local:8080/frame"
        - name: URL_K8S_SUFFIX
          value: ".default.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3