apiVersion: v1
kind: Service
metadata:
  name: face-recognition
  labels:
    app: face-recognition
    service: face-recognition
    project: airport
spec:
  selector:
    app: face-recognition
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-deploy
  labels:
    app: face-recognition
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition
      version: v1
  template:
    metadata:
      labels:
        app: face-recognition
        version: v1
    spec:
      containers:
      - name: face-recognition
        image: van15h/face-recognition:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3