apiVersion: v1
kind: Service
metadata:
  name: image-analysis
  labels:
    app: image-analysis
    service: image-analysis
    project: airport
spec:
  selector:
    app: image-analysis
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analysis-deploy
  labels:
    app: image-analysis
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analysis
      version: v1
  template:
    metadata:
      labels:
        app: image-analysis
        version: v1
    spec:
      containers:
      - name: image-analysis
        image: van15h/image-analysis:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1500m"