apiVersion: v1
kind: Service
metadata:
  name: image-analysis
  labels:
    app: image-analysis
    service: image-analysis
spec:
  # type: NodePort
  selector:
    app: image-analysis
  ports:
  - name: http
    # protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analysis-deploy
  labels:
    app: image-analysis
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analysis
      version: v1
  template:
    metadata:
      labels:
        app: image-analysis
        version: v1
    spec:
      containers:
      - name: image-analysis
        image: ccuni/image-analysis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080