apiVersion: v1
kind: Service
metadata:
  name: momentum
  labels:
    app: momentum
    service: momentum
    project: airport
spec:
  selector:
    app: momentum
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momentum-deploy
  labels:
    app: momentum
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momentum
      version: v1
  template:
    metadata:
      labels:
        app: momentum
        version: v1
    spec:
      containers:
      - name: momentum
        image: van15h/momentum:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3