apiVersion: v1
kind: Service
metadata:
  name: section-1
  labels:
    app: section-1
    service: section-1
spec:
  selector:
    app: section-1
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-1-deploy
  labels:
    app: section-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section-1
      version: v1
  template:
    metadata:
      labels:
        app: section-1
        version: v1
    spec:
      containers:
      - name: section-1
        image: van15h/section:v1
        imagePullPolicy: Always
        env:
        - name: SECTION
          value: "1"
        ports:
          - containerPort: 8080