apiVersion: v1
kind: Service
metadata:
  name: section-1
  labels:
    app: section-1
    service: section-1
    project: airport
spec:
  selector:
    app: section-1
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-1-deploy
  labels:
    app: section-1
    version: v1
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section-1
      version: v1
  template:
    metadata:
      labels:
        app: section-1
        version: v1
    spec:
      containers:
      - name: section-1
        image: van15h/section:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SECTION
          value: "1"
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 7
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 7
          timeoutSeconds: 3