apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    project: airport
spec:
  # type: NodePort
  selector:
    app: alerts
  ports:
  - name: alerts
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30000