apiVersion: v1
kind: Service
metadata:
  name: cpanel
  labels:
    project: airport
spec:
  type: NodePort
  selector:
    app: cpanel
  ports:
  - name: cpanel
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002