apiVersion: v1
kind: Service
metadata:
  name: image-analysis
  labels:
    project: airport
spec:
  # type: NodePort
  selector:
    app: image-analysis
  ports:
  - name: image-analysis
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30004