apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: alerts
spec:
  host: alerts
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cpanel
spec:
  host: cpanel
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: collector
spec:
  host: collector
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: section-1
spec:
  host: section-1
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: camera-agent-1
spec:
  host: camera-agent-1
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: camera-agent-2
spec:
  host: camera-agent-2
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: face-recognition
spec:
  host: face-recognition
  subsets:
  - name: v1
    labels:
      version: v1