apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: alerts
spec:
  host: alerts
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cpanel
spec:
  host: cpanel
  subsets:
  - name: v1
    labels:
      version: v1