apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cpanel
spec:
  hosts:
  - cpanel
  http:
  - route:
    - destination:
        host: cpanel
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alerts
spec:
  hosts:
  - alerts
  http:
  - route:
    - destination:
        host: alerts
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: collector
spec:
  hosts:
  - collector
  http:
  - route:
    - destination:
        host: collector
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: section-1
spec:
  hosts:
  - section-1
  http:
  - route:
    - destination:
        host: section-1
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: camera-agent-1
spec:
  hosts:
  - camera-agent-1
  http:
  - route:
    - destination:
        host: camera-agent-1
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: camera-agent-2
spec:
  hosts:
  - camera-agent-2
  http:
  - route:
    - destination:
        host: camera-agent-2
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: face-recognition
spec:
  hosts:
  - face-recognition
  http:
  - route:
    - destination:
        host: face-recognition
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: image-analysis
spec:
  hosts:
  - image-analysis
  http:
  - route:
    - destination:
        host: image-analysis
        subset: v1