apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: momentum
spec:
  hosts:
  - momentum.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: momentum.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alerts
spec:
  hosts:
  - alerts.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: alerts.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: section-1
spec:
  hosts:
  - section-1.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: section-1.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: collector
spec:
  hosts:
  - collector.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: collector.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: camera-agent-1
spec:
  hosts:
  - camera-agent-1.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: camera-agent-1.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: camera-agent-2
spec:
  hosts:
  - camera-agent-2.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: camera-agent-2.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: face-recognition
spec:
  hosts:
  - face-recognition.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: face-recognition.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: image-analysis
spec:
  hosts:
  - image-analysis.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: image-analysis.default.svc.cluster.local
        subset: v1