apiVersion: v1
kind: Service
metadata:
  name: alerts
  labels:
    project: airport
    app: alerts
    service: alerts
spec:
  # type: NodePort
  selector:
    app: alerts
  ports:
  - name: alerts
    protocol: HTTP
    port: 8080
    targetPort: 8080
    # nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-deploy
  labels:
    project: airport
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
      - name: alerts
        image: van15h/alerts
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
