apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
      - name: alerts
        image: van15h/alerts
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
