apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app: collector
    service: collector
spec:
  # type: NodePort
  selector:
    app: collector
  ports:
  - name: http
    # protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deploy
  labels:
    app: collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
      version: v1
  template:
    metadata:
      labels:
        app: collector
        version: v1
    spec:
      containers:
      - name: collector
        image: van15h/collector:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: URL_ALERTS
          value: "http://alerts:8080"
        - name: URL_IMAGE_ANALYZE
          value: "http://image-analysis:8080/frame"
        - name: URL_FACE_RECOGNITION
          value: "http://face-recognition:8080/frame"
