apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpanel-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpanel
  template:
    metadata:
      labels:
        app: cpanel
    spec:
      containers:
      - name: cpanel
        image: van15h/cpanel
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
