apiVersion: v1
kind: Service
metadata:
  name: cpanel
  labels:
    app: cpanel
    service: cpanel
spec:
  # type: NodePort
  selector:
    app: cpanel
  ports:
  - name: http
    # protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpanel-deploy
  labels:
    app: cpanel
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpanel
      version: v1
  template:
    metadata:
      labels:
        app: cpanel
        version: v1
    spec:
      containers:
      - name: cpanel
        image: van15h/cpanel:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
