apiVersion: v1
kind: Service
metadata:
  name: face-recognition
  labels:
    app: face-recognition
    service: face-recognition
spec:
  # type: NodePort
  selector:
    app: face-recognition
  ports:
  - name: http
    # protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-deploy
  labels:
    app: face-recognition
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition
      version: v1
  template:
    metadata:
      labels:
        app: face-recognition
        version: v1
    spec:
      containers:
      - name: face-recognition
        image: ccuni/face-recognition:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080