apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-1-deploy
  labels:
    project: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section-1
  template:
    metadata:
      labels:
        app: section-1
    spec:
      containers:
      - name: section-1
        image: van15h/section
        env:
        - name: SECTION
          value: "1"
        ports:
          - containerPort: 8080