apiVersion: v1
kind: Service
metadata:
  name: face-recognition
  labels:
    project: airport
spec:
  # type: NodePort
  selector:
    app: face-recognition
  ports:
  - name: face-recognition
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30003